-- MySQL Script generated by MySQL Workbench
-- Sun Apr 18 21:01:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thechamber
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `thechamber` ;

-- -----------------------------------------------------
-- Schema thechamber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thechamber` DEFAULT CHARACTER SET utf8 ;
USE `thechamber` ;

-- -----------------------------------------------------
-- Table `thechamber`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`roles` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`roles` (
  `rolid` INT NOT NULL,
  `rolName` VARCHAR(45) NULL,
  PRIMARY KEY (`rolid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`account` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`account` (
  `accountId` INT NOT NULL AUTO_INCREMENT,
  `rolid` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(56) NOT NULL,
  `curp` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`accountId`),
  INDEX `fk_account_roles_idx` (`rolid` ASC) VISIBLE,
  CONSTRAINT `fk_account_roles`
    FOREIGN KEY (`rolid`)
    REFERENCES `thechamber`.`roles` (`rolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `thechamber`.`experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`experience` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`experience` (
  `experienceId` INT NOT NULL,
  `experienceName` VARCHAR(45) NULL,
  PRIMARY KEY (`experienceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`profile` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`profile` (
  `profileId` INT NOT NULL,
  `profileName` VARCHAR(45) NULL,
  PRIMARY KEY (`profileId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`reviewStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`reviewStatus` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`reviewStatus` (
  `reviewStatusId` INT NOT NULL,
  `reviewStatusName` VARCHAR(45) NULL,
  PRIMARY KEY (`reviewStatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`applicant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`applicant` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`applicant` (
  `applicantId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `experienceId` INT NOT NULL,
  `profileId` INT NOT NULL,
  `reviewStatusId` INT NOT NULL,
  PRIMARY KEY (`applicantId`),
  INDEX `fk_applicant_experience1_idx` (`experienceId` ASC) VISIBLE,
  INDEX `fk_applicant_profile1_idx` (`profileId` ASC) VISIBLE,
  INDEX `fk_applicant_reviewStatus1_idx` (`reviewStatusId` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_experience1`
    FOREIGN KEY (`experienceId`)
    REFERENCES `thechamber`.`experience` (`experienceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_profile1`
    FOREIGN KEY (`profileId`)
    REFERENCES `thechamber`.`profile` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_reviewStatus1`
    FOREIGN KEY (`reviewStatusId`)
    REFERENCES `thechamber`.`reviewStatus` (`reviewStatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`testStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`testStatus` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`testStatus` (
  `statusId` INT NOT NULL AUTO_INCREMENT,
  `testStatusName` VARCHAR(45) NULL,
  PRIMARY KEY (`statusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`tests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`tests` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`tests` (
  `testId` INT NOT NULL AUTO_INCREMENT,
  `accountId` INT NOT NULL,
  `testStatus_statusId` INT NOT NULL,
  `beganAtTimeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `duration` INT NULL,
  `finishedAtTimeStamp` TIMESTAMP NULL,
  `overallScore` INT NULL,
  PRIMARY KEY (`testId`),
  INDEX `fk_pruebas_account1_idx` (`accountId` ASC) VISIBLE,
  INDEX `fk_tests_testStatus1_idx` (`testStatus_statusId` ASC) VISIBLE,
  CONSTRAINT `fk_pruebas_account1`
    FOREIGN KEY (`accountId`)
    REFERENCES `thechamber`.`account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_testStatus1`
    FOREIGN KEY (`testStatus_statusId`)
    REFERENCES `thechamber`.`testStatus` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`applicant_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`applicant_account` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`applicant_account` (
  `joinid` INT NOT NULL,
  `applicant_idapplicant` INT NOT NULL,
  `account_accountId` INT NOT NULL,
  PRIMARY KEY (`joinid`),
  INDEX `fk_applicant_account_applicant1_idx` (`applicant_idapplicant` ASC) VISIBLE,
  INDEX `fk_applicant_account_account1_idx` (`account_accountId` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_account_applicant1`
    FOREIGN KEY (`applicant_idapplicant`)
    REFERENCES `thechamber`.`applicant` (`applicantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_account_account1`
    FOREIGN KEY (`account_accountId`)
    REFERENCES `thechamber`.`account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`softSkills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`softSkills` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`softSkills` (
  `softskillId` INT NOT NULL AUTO_INCREMENT,
  `softSkillName` VARCHAR(45) NULL,
  PRIMARY KEY (`softskillId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`levelNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`levelNames` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`levelNames` (
  `levelId` INT NOT NULL AUTO_INCREMENT,
  `levelName` VARCHAR(45) NULL,
  PRIMARY KEY (`levelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`puzzleNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`puzzleNames` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`puzzleNames` (
  `puzzleId` INT NOT NULL AUTO_INCREMENT,
  `puzzleName` VARCHAR(45) NULL,
  PRIMARY KEY (`puzzleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`checkpoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`checkpoints` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`checkpoints` (
  `checkpointId` INT NOT NULL AUTO_INCREMENT,
  `test_testId` INT NOT NULL,
  `checkpointScore` INT NULL,
  `checkpointMaxScore` INT NULL,
  `softSkillId` INT NOT NULL,
  `levelId` INT NOT NULL,
  `puzzleId` INT NOT NULL,
  `timeElapsed` INT NULL,
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`checkpointId`),
  INDEX `fk_checkpoints_pruebas1_idx` (`test_testId` ASC) VISIBLE,
  INDEX `fk_checkpoints_softSkill1_idx` (`softSkillId` ASC) VISIBLE,
  INDEX `fk_checkpoints_levelNames1_idx` (`levelId` ASC) VISIBLE,
  INDEX `fk_checkpoints_puzzleName1_idx` (`puzzleId` ASC) VISIBLE,
  CONSTRAINT `fk_checkpoints_pruebas1`
    FOREIGN KEY (`test_testId`)
    REFERENCES `thechamber`.`tests` (`testId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_softSkill1`
    FOREIGN KEY (`softSkillId`)
    REFERENCES `thechamber`.`softSkills` (`softskillId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_levelNames1`
    FOREIGN KEY (`levelId`)
    REFERENCES `thechamber`.`levelNames` (`levelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_puzzleName1`
    FOREIGN KEY (`puzzleId`)
    REFERENCES `thechamber`.`puzzleNames` (`puzzleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`scores` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`scores` (
  `scoreId` INT NOT NULL AUTO_INCREMENT,
  `test_testId` INT NOT NULL,
  `softSkill_idsoftSkill` INT NOT NULL,
  `softSkillScore` INT NULL,
  PRIMARY KEY (`scoreId`),
  INDEX `fk_scores_test1_idx` (`test_testId` ASC) VISIBLE,
  INDEX `fk_scores_softSkill1_idx` (`softSkill_idsoftSkill` ASC) VISIBLE,
  CONSTRAINT `fk_scores_test1`
    FOREIGN KEY (`test_testId`)
    REFERENCES `thechamber`.`tests` (`testId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scores_softSkill1`
    FOREIGN KEY (`softSkill_idsoftSkill`)
    REFERENCES `thechamber`.`softSkills` (`softskillId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
