-- MySQL Script generated by MySQL Workbench
-- Fri Apr 16 16:29:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thechamber
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `thechamber` ;

-- -----------------------------------------------------
-- Schema thechamber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thechamber` DEFAULT CHARACTER SET utf8 ;
USE `thechamber` ;

-- -----------------------------------------------------
-- Table `thechamber`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`roles` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`roles` (
  `rolid` INT NOT NULL,
  `rolName` VARCHAR(45) NULL,
  PRIMARY KEY (`rolid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`account` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`account` (
  `accountId` INT NOT NULL AUTO_INCREMENT,
  `rolid` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(56) NOT NULL,
  `curp` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`accountId`),
  INDEX `fk_account_roles_idx` (`rolid` ASC) VISIBLE,
  CONSTRAINT `fk_account_roles`
    FOREIGN KEY (`rolid`)
    REFERENCES `thechamber`.`roles` (`rolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `thechamber`.`experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`experience` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`experience` (
  `experienceId` INT NOT NULL,
  `experienceName` VARCHAR(45) NULL,
  PRIMARY KEY (`experienceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`profile` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`profile` (
  `profileId` INT NOT NULL,
  `profileName` VARCHAR(45) NULL,
  PRIMARY KEY (`profileId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`reviewStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`reviewStatus` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`reviewStatus` (
  `reviewStatusId` INT NOT NULL,
  `reviewStatusName` VARCHAR(45) NULL,
  PRIMARY KEY (`reviewStatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`applicant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`applicant` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`applicant` (
  `idapplicant` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `experienceId` INT NOT NULL,
  `profileId` INT NOT NULL,
  `reviewStatusId` INT NOT NULL,
  PRIMARY KEY (`idapplicant`),
  INDEX `fk_applicant_experience1_idx` (`experienceId` ASC) VISIBLE,
  INDEX `fk_applicant_profile1_idx` (`profileId` ASC) VISIBLE,
  INDEX `fk_applicant_reviewStatus1_idx` (`reviewStatusId` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_experience1`
    FOREIGN KEY (`experienceId`)
    REFERENCES `thechamber`.`experience` (`experienceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_profile1`
    FOREIGN KEY (`profileId`)
    REFERENCES `thechamber`.`profile` (`profileId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_reviewStatus1`
    FOREIGN KEY (`reviewStatusId`)
    REFERENCES `thechamber`.`reviewStatus` (`reviewStatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`test` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`test` (
  `idpruebas` INT NOT NULL AUTO_INCREMENT,
  `accountId` INT NOT NULL,
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpruebas`),
  INDEX `fk_pruebas_account1_idx` (`accountId` ASC) VISIBLE,
  CONSTRAINT `fk_pruebas_account1`
    FOREIGN KEY (`accountId`)
    REFERENCES `thechamber`.`account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`applicant_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`applicant_account` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`applicant_account` (
  `joinid` INT NOT NULL,
  `applicant_idapplicant` INT NOT NULL,
  `account_accountId` INT NOT NULL,
  PRIMARY KEY (`joinid`),
  INDEX `fk_applicant_account_applicant1_idx` (`applicant_idapplicant` ASC) VISIBLE,
  INDEX `fk_applicant_account_account1_idx` (`account_accountId` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_account_applicant1`
    FOREIGN KEY (`applicant_idapplicant`)
    REFERENCES `thechamber`.`applicant` (`idapplicant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_account_account1`
    FOREIGN KEY (`account_accountId`)
    REFERENCES `thechamber`.`account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`softSkill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`softSkill` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`softSkill` (
  `idsoftSkill` INT NOT NULL AUTO_INCREMENT,
  `softSkillName` VARCHAR(45) NULL,
  PRIMARY KEY (`idsoftSkill`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`levelNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`levelNames` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`levelNames` (
  `idlevel` INT NOT NULL,
  `levelName` VARCHAR(45) NULL,
  PRIMARY KEY (`idlevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`puzzleName`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`puzzleName` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`puzzleName` (
  `idPuzzle` INT NOT NULL,
  `puzzleName` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuzzle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thechamber`.`checkpoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thechamber`.`checkpoints` ;

CREATE TABLE IF NOT EXISTS `thechamber`.`checkpoints` (
  `checkpointid` INT NOT NULL AUTO_INCREMENT,
  `idprueba` INT NOT NULL,
  `score` INT NULL,
  `maxScore` INT NULL,
  `idsoftSkill` INT NOT NULL,
  `idlevel` INT NOT NULL,
  `idPuzzle` INT NOT NULL,
  `timeElapsed` INT NULL,
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`checkpointid`),
  INDEX `fk_checkpoints_pruebas1_idx` (`idprueba` ASC) VISIBLE,
  INDEX `fk_checkpoints_softSkill1_idx` (`idsoftSkill` ASC) VISIBLE,
  INDEX `fk_checkpoints_levelNames1_idx` (`idlevel` ASC) VISIBLE,
  INDEX `fk_checkpoints_puzzleName1_idx` (`idPuzzle` ASC) VISIBLE,
  CONSTRAINT `fk_checkpoints_pruebas1`
    FOREIGN KEY (`idprueba`)
    REFERENCES `thechamber`.`test` (`idpruebas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_softSkill1`
    FOREIGN KEY (`idsoftSkill`)
    REFERENCES `thechamber`.`softSkill` (`idsoftSkill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_levelNames1`
    FOREIGN KEY (`idlevel`)
    REFERENCES `thechamber`.`levelNames` (`idlevel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkpoints_puzzleName1`
    FOREIGN KEY (`idPuzzle`)
    REFERENCES `thechamber`.`puzzleName` (`idPuzzle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
